module.exports.albums = [

	'All Greek To Me',
	'An Arm and a Leg',
	'Back to Square One',
	'Back To the Drawing Board',
	'Beating a Dead Horse',
	'Beating Around the Bush',
	'Between a Rock and a Hard Place',
	'Birds of a Feather Flock Together',
	'A Bite at the Cherry',
	'Break The Ice',
	'Burst Your Bubble',
	'A Busy Bee',
	'A Cat Nap',
	'A Chip on Your Shoulder',
	'Close But No Cigar',
	'A Cold Day in Hell',
	'A Cold Fish',
	'Cry Over Spilt Milk',
	'Cry Wolf',
	'Cup Of Joe',
	'Curiosity Killed The Cat',
	'A Cut Above',
	'A Cut Below',
	'Cut The Mustard',
	'Cut To The Chase',
	'A Day Late and a Dollar Short',
	'A Dog in the Manger',
	'Don\'t Look a Gift Horse In The Mouth',
	'Down And Out',
	'Down For The Count',
	'Down To Earth',
	'Dropping Like Flies',
	'Elephant in the Room',
	'Elvis Has Left The Building',
	'Everything But The Kitchen Sink',
	'A Few Sandwiches Short of a Picnic',
	'Fight Fire With Fire',
	'Fit as a Fiddle',
	'Fool\'s Gold',
	'A Fool and His Money are Soon Parted',
	'Give a Man a Fish',
	'Go For Broke',
	'Goody Two-Shoes',
	'Greased Lightning',
	'A Hair’s Breadth',
	'Hands Down',
	'Happy as a Clam',
	'Hard Pill to Swallow',
	'Heads Up',
	'Hear, Hear',
	'High And Dry',
	'Hit Below The Belt',
	'A Home Bird',
	'If You Can\'t Stand the Heat, Get Out of the Kitchen',
	'In a Pickle',
	'In the Red',
	'I Smell a Rat',
	'It\'s Not All It\'s Cracked Up To Be',
	'It\'s Not Brain Surgery',
	'Jack of All Trades Master of None',
	'Jaws of Death',
	'Jig Is Up',
	'Jumping the Gun',
	'Keep On Truckin\'',
	'Keep Your Eyes Peeled',
	'Keep Your Shirt On',
	'Knock Your Socks Off',
	'Know the Ropes',
	'Knuckle Down',
	'A Leg Up',
	'A Lemon',
	'Let Her Rip',
	'Lickety Split',
	'A Little Bird Told Me',
	'A Little from Column A, a Little from Column B',
	'A Lone Wolf',
	'A Lot on One’s Plate',
	'Love Birds',
	'Lovey Dovey',
	'Man of Few Words',
	'Money Doesn\'t Grow On Trees',
	'Mountain Out of a Molehill',
	'Mouth-Watering',
	'Needle In a Haystack',
	'No Ifs, Ands, or Buts',
	'Not the Sharpest Tool in the Shed',
	'Off One\'s Base',
	'On Cloud Nine',
	'On the Ropes',
	'On the Same Page',
	'A Piece of Cake',
	'Playing For Keeps',
	'The Plot Thickens',
	'Poke Fun At',
	'Put a Sock In It',
	'Quick and Dirty',
	'Raining Cats and Dogs',
	'Rain on Your Parade',
	'Read \'Em and Weep',
	'Ride Him, Cowboy!',
	'Right Off the Bat',
	'Right Out of the Gate',
	'Ring Any Bells?',
	'Scot-Free',
	'Short End of the Stick',
	'Son of a Gun',
	'Swinging For the Fences',
	'There\'s No I in Team',
	'Throw In the Towel',
	'Top Drawer',
	'Tough It Out',
	'Tug of War',
	'Two Down, One to Go',
	'Ugly Duckling',
	'Under the Weather',
	'Up In Arms',
	'What Am I, Chopped Liver?',
	'When the Rubber Hits the Road',
	'Yada Yada',
	'You Can\'t Judge a Book By Its Cover',
	'You Can\'t Teach an Old Dog New Tricks',


]


module.exports.artist_first_word = [

	'Aberrant',
	'Absent',
	'Abstracted',
	'Accessible',
	'Ahead',
	'Alluring',
	'Ambiguous',
	'Apathetic',
	'Aromatic',
	'Ashamed',
	'Asleep',
	'Aspiring',
	'Broad',
	'Capricious',
	'Chemical',
	'Clammy',
	'Complete',
	'Comprehensive',
	'Concerned',
	'Dark',
	'Dependent',
	'Descriptive',
	'Direful',
	'Eastern',
	'Easy',
	'Eatable',
	'Educational',
	'Electric',
	'Eminent',
	'Erratic',
	'Exotic',
	'Feeble',
	'Festive',
	'First',
	'Fixed',
	'Flaky',
	'Flashy',
	'Flimsy',
	'Foreign',
	'Frequent',
	'Fumbling',
	'Futuristic',
	'Glib',
	'Grateful',
	'Grey',
	'Gruesome',
	'Half',
	'Halting',
	'Hard',
	'Hurt',
	'Illegal',
	'Imaginary',
	'Inconclusive',
	'Informal',
	'Inner',
	'Instinctive',
	'Irritating',
	'Jaded',
	'Jazzy',
	'Juvenile',
	'Knotty',
	'Labored',
	'Lackadaisical',
	'Last',
	'Limping',
	'Lonely',
	'Loose',
	'Ludicrous',
	'Maniacal',
	'Materialistic',
	'Measly',
	'Mere',
	'Mysterious',
	'Narrow',
	'Nippy',
	'Nonchalant',
	'Nutritious',
	'Nutty',
	'Obscene',
	'Obsequious',
	'Old-Fashioned',
	'Oval',
	'Pastoral',
	'Pathetic',
	'Penitent',
	'Plain',
	'Plastic',
	'Plucky',
	'Powerful',
	'Previous',
	'Productive',
	'Psychedelic',
	'Psychotic',
	'Purple',
	'Quick',
	'Quizzical',
	'Rainy',
	'Reflective',
	'Regular',
	'Resonant',
	'Responsible',
	'Ripe',
	'Scintillating',
	'Several',
	'Shy',
	'Six',
	'Smart',
	'Smelly',
	'Soft',
	'Somber',
	'Spiky',
	'Splendid',
	'Sticky',
	'Sturdy',
	'Subdued',
	'Suspicious',
	'Sweltering',
	'Swift',
	'Tested',
	'Therapeutic',
	'Third',
	'Three',
	'Tightfisted',
	'Tiny',
	'Toothsome',
	'Tranquil',
	'Tremendous',
	'Unable',
	'Unadvised',
	'Uncovered',
	'Unequal',
	'Uneven',
	'Uppity',
	'Utter',
	'Various',
	'Vigorous',
	'Well-to-Do',
	'Wistful',
	'Woozy',
	'Wrong',

]


module.exports.artist_second_word = [

	'Accident',
	'Activity',
	'Advice',
	'Airport',
	'Analysis',
	'Apple',
	'Argument',
	'Association',
	'Awareness',
	'Basket',
	'Bedroom',
	'Bird',
	'Bonus',
	'Breath',
	'Buyer',
	'Cabinet',
	'Camera',
	'Cell',
	'Chest',
	'Childhood',
	'Chocolate',
	'City',
	'Coffee',
	'Committee',
	'Computer',
	'Confusion',
	'Contract',
	'Control',
	'Cousin',
	'Criticism',
	'Customer',
	'Dad',
	'Data',
	'Development',
	'Device',
	'Diamond',
	'Direction',
	'Disaster',
	'Drama',
	'Drawer',
	'Drawing',
	'Ear',
	'Editor',
	'Education',
	'Efficiency',
	'Effort',
	'Elevator',
	'Emphasis',
	'Employer',
	'Employment',
	'Entertainment',
	'Exam',
	'Excitement',
	'Family',
	'Finding',
	'Fishing',
	'Gate',
	'Government',
	'Grandmother',
	'Growth',
	'Hall',
	'Hamburger',
	'Health',
	'Hearing',
	'Height',
	'Highway',
	'Historian',
	'Honey',
	'Housing',
	'Importance',
	'Independence',
	'Insect',
	'Inspector',
	'Lab',
	'Location',
	'Mall',
	'Math',
	'Meat',
	'Member',
	'Midnight',
	'Moment',
	'Mud',
	'Music',
	'Nation',
	'Office',
	'Operation',
	'Opinion',
	'Orange',
	'Organization',
	'Outcome',
	'Oven',
	'Owner',
	'Paper',
	'Passion',
	'Patience',
	'Perception',
	'Performance',
	'Person',
	'Perspective',
	'Phone',
	'Pizza',
	'Poetry',
	'Power',
	'Preference',
	'President',
	'Professor',
	'Property',
	'Ratio',
	'Reaction',
	'Recording',
	'Refrigerator',
	'River',
	'Secretary',
	'Selection',
	'Significance',
	'Society',
	'Song',
	'Soup',
	'Speaker',
	'Statement',
	'Storage',
	'Story',
	'Strategy',
	'Studio',
	'System',
	'Teacher',
	'Thanks',
	'Theory',
	'Tongue',
	'Trainer',
	'Two',
	'Union',
	'Unit',
	'User',
	'Variation',
	'Video',
	'Village',
	'Way',
	'Woman',
	'Writer',

]


module.exports.album_art = [
	'/images/art-1.jpg',
	'/images/art-2.jpg',
	'/images/art-3.jpg',
	'/images/art-4.jpg',
	'/images/art-5.jpg',
	'/images/art-6.jpg',
	'/images/art-7.jpg',
	'/images/art-8.jpg',
	'/images/art-9.jpg',
	'/images/art-10.jpg',
	'/images/art-11.jpg',
	'/images/art-12.jpg'
]